version: '3.8'
services:
  db:
    image: weegedocker/dbcadastro
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbcadastro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword 
      MYSQL_DATABASE: UsuarioDb 
      MYSQL_USER: Root 
      MYSQL_PASSWORD: Root

    cap_add:
      - SYS_NICE
  api:
    image: weegedocker/cadastrousuario
    container_name: cadastrousuario_api
    restart: always
    ports:
      - "8080:44319"
    depends_on:
      - db