
CREATE SCHEMA IF NOT EXISTS `UsuarioDb` DEFAULT CHARACTER SET utf8mb4 ;
USE `UsuarioDb` ;


CREATE TABLE IF NOT EXISTS `UsuarioDb`.`Log` (
  `Id` VARCHAR(255) NOT NULL,
  `Log` VARCHAR(100) NOT NULL,
  `Operacao` INT(11) NOT NULL,
  `DataDaOperacao` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



CREATE TABLE IF NOT EXISTS `UsuarioDb`.`Usuario` (
  `Id` VARCHAR(255) NOT NULL,
  `FirstName` LONGTEXT NOT NULL,
  `SurName` LONGTEXT NULL DEFAULT NULL,
  `Age` INT(11) NOT NULL,
  `CreationDate` DATETIME(6) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



